export const projects = [
  {
    title: 'Caremada Dashboard',
    description: "Caremada is a hub for caregivers and care receivers to come together. Professional caregivers can build their profiles, find work, and get paid for their services to those in need. Using Vue.js & MySQL Workbench to design and build a Dasboard and a Reporting system for Caremada to monitor their userbase. (At the moment, we can not disclose the source code of the project). ",
    image: '/images/Caremada.jpg',
    tags: ['Vue.js', 'Axios', 'MySQL Workbench'],
    source: '/',
    visit: 'https://caremada.com/',
    id: 0,
  },
  {
    title: 'Space Shooter',
    description: "A simple top down arcade style shooter using basic assets provided by Unity technologies, built-in components and wrting custom code. ",
    image: '/images/SpaceShooter.PNG',
    tags: ['C#', 'Unity'],
    source: 'https://github.com/dang0107/SpaceShooter',
    visit: '/games/SpaceShooter/index.html',
    id: 1,
  },
  {
    title: 'Clock',
    description: "A simple time display using Unity and C# to animate the arms of a clock. ",
    image: '/images/Clock.PNG',
    tags: ['C#', 'Unity'],
    source: 'https://github.com/dang0107/Clock',
    visit: '/games/Clock/index.html',
    id: 2,
  },
  {
    title: 'Roll A Ball',
    description: "A game using Unity Editor and its built-in capabilitites to set up a simple game environment and C#.",
    image: '/images/RollABall.PNG',
    tags: ['C#', 'Unity'],
    source: 'https://github.com/dang0107/RollABall',
    visit: '/games/RollABall/index.html',
    id: 3,
  },

  {
    title: 'Gauntlet Runner',
    description: "This is a 3D gauntlet running game, you will be playing as a robot running as far as possible through a gauntlet tunnel, attempting to grab power ups to extend your game time. You need to avoid obstacles that will slow you down.The game ends when you run out of time.",
    image: '/images/GauntletRunner.PNG',
    tags: ['C#', 'Unity'],
    source: 'https://github.com/dang0107/GauntletRunner',
    visit: '/games/GauntletRunner/index.html',
    id: 4,
  },
  {
    title: 'School Community Website',
    description: "This is a website perfoms CRUD commands on the Students and Communities or uploads ads onto the Communities by storing them on BlobStorge.",
    image: '/images/SchoolCommunity.PNG',
    tags: ['C#', 'HTML', 'CSS', 'Azure'],
    source: 'https://github.com/dang0107/School-Community-Website',
    visit: 'http://kimschoolcommunity.azurewebsites.net/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Crew Memeber of Ipho Vietnamese Restaurant', },
  { year: '01.2019', text: 'Student Application Support at Payments Canada (Co-op experience)', },
  { year: '12.2019', text: 'Graduated with a Diploma degree in Computer Programming', },
  { year: 2020, text: 'Pursued higher diploma at Algonquin College in Computer Engineering', },
  { year: 2021, text: 'Graduated with an Advanced Diploma degree in Computer Engineering', },
];